installation_dir = "/data/data/com.termux.nix/files/usr"
[[environment]]
name = "EDITOR"
value = "hx"

[[environment]]
name = "GC_NPROCS"
value = "1"

[[environment]]
name = "HOME"
value = "/data/data/com.termux.nix/files/home"

[[environment]]
name = "LANG"
value = "en_US.UTF-8"

[[environment]]
name = "LESSKEYIN_SYSTEM"
value = "/nix/store/w7nc6jpqmy8nknha2dywmc03klxpmnvs-lessconfig"

[[environment]]
name = "LIBEXEC_PATH"
value = "/data/data/com.termux.nix/files/home/.nix-profile/libexec:/data/data/com.termux.nix/files/home/.local/state/nix/profile/libexec:/etc/profiles/per-user/nix-on-droid/libexec:/nix/var/nix/profiles/default/libexec:/run/current-system/sw/libexec"

[[environment]]
name = "LOCALE_ARCHIVE"
value = "/nix/store/h3h6bz85hc2jz5zy79xgwhm9yxm61z7b-glibc-locales-2.42-61/lib/locale/locale-archive"

[[environment]]
name = "NIXPKGS_CONFIG"
value = "/etc/nix/nixpkgs-config.nix"

[[environment]]
name = "NIX_CONFIG"
value = "experimental-features = nix-command flakes"

[[environment]]
name = "PAGER"
value = "less"

[[environment]]
name = "PATH"
value = "/data/data/com.termux.nix/files/home/.nix-profile/bin:/data/data/com.termux.nix/files/home/.local/state/nix/profile/bin:/etc/profiles/per-user/nix-on-droid/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"

[[environment]]
name = "TZDIR"
value = "/etc/zoneinfo"

[[environment]]
name = "USER"
value = "nix-on-droid"

[[environment]]
name = "XDG_CONFIG_DIRS"
value = "/etc/xdg:/data/data/com.termux.nix/files/home/.nix-profile/etc/xdg:/data/data/com.termux.nix/files/home/.local/state/nix/profile/etc/xdg:/etc/profiles/per-user/nix-on-droid/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg"

[[environment]]
name = "XDG_DATA_DIRS"
value = "/data/data/com.termux.nix/files/home/.nix-profile/share:/data/data/com.termux.nix/files/home/.local/state/nix/profile/share:/etc/profiles/per-user/nix-on-droid/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share"

[first_run]
enable = true
fallback_shell = "/data/data/com.termux.nix/files/usr/bin/sh"
[[first_run.commands]]
argv = ["--switch-profile", "/nix/var/nix/profiles/system"]
argv0 = "/nix/store/16yqm9lwrf0n11k3sphl2i8dp9r4k4kd-nix-2.34.7/bin/nix-env"

[[first_run.commands]]
argv = [
  "--extra-experimental-features",
  "nix-command",
  "--extra-experimental-features",
  "flakes",
  "flake",
  "new",
  "/data/data/com.termux.nix/files/home/.config/nix-on-droid/template",
  "--template",
  "github:kyehn/nix-on-droid/unstable",
]
argv0 = "/nix/store/16yqm9lwrf0n11k3sphl2i8dp9r4k4kd-nix-2.34.7/bin/nix"

[[first_run.commands]]
argv = [
  "--extra-experimental-features",
  "nix-command",
  "--extra-experimental-features",
  "flakes",
  "run",
  "nixpkgs#nixos-rebuild-ng",
  "--",
  "switch",
  "--flake",
  "/data/data/com.termux.nix/files/home/.config/nix-on-droid/template#default",
  "--impure",
  "--accept-flake-config",
  "--verbose",
  "--print-build-logs",
  "--show-trace",
  "--use-substitutes",
]
argv0 = "/nix/store/16yqm9lwrf0n11k3sphl2i8dp9r4k4kd-nix-2.34.7/bin/nix"

[[first_run.environment]]
name = "GC_NPROCS"
value = "1"

[[first_run.environment]]
name = "NIXOS_REBUILD_I_UNDERSTAND_THE_CONSEQUENCES_PLEASE_BREAK_MY_SYSTEM"
value = "1"

[process_compose]
binary_path = "/nix/store/6y7zn1hzqz9w2prrihzg3fiazhaqaa98-process-compose-1.110.0/bin/process-compose"
config_path = "/nix/store/96n1zv7fyp5qy44wk8vcq2klvwhxvf60-process-compose.yaml"
enable = false
extra_args = ["--disable-dotenv", "--no-server", "--read-only", "-t=false"]

[user]
home = "/data/data/com.termux.nix/files/home"
name = "nix-on-droid"
shell = "/nix/store/kqh7aw6sj1b0kzfkx2fxm8ij4lkc0735-bash-interactive-5.3p9/bin/bash"
