{
  config,
  writeScript,
  writeText,
}:

let
  fakeProcStat = writeText "fakeProcStat" ''
    btime 0
  '';
  fakeProcUptime = writeText "fakeProcUptime" ''
    0.00 0.00
  '';
in
writeScript "login" ''
  #!/system/bin/sh
  # This file is generated by Nix-on-Droid. DO NOT EDIT.
  set -eu -o pipefail

  export USER="${config.user.userName}"
  export HOME="${config.user.home}"
  export PROOT_TMP_DIR=${config.build.installationDir}/tmp
  export PROOT_L2S_DIR=${config.build.installationDir}/.l2s

  if ! /system/bin/pgrep proot-static > /dev/null; then
    if test -e ${config.build.installationDir}/bin/.proot-static.new; then
      echo "Installing new proot-static..."
      /system/bin/mv ${config.build.installationDir}/bin/.proot-static.new ${config.build.installationDir}/bin/proot-static
    fi

    if test -e ${config.build.installationDir}/usr/lib/.login-inner.new; then
      echo "Installing new login-inner..."
      /system/bin/mv ${config.build.installationDir}/usr/lib/.login-inner.new ${config.build.installationDir}/usr/lib/login-inner
    fi
  fi

  if [ ! -r /proc/stat ] && [ -e ${config.build.installationDir}${fakeProcStat} ]; then
    BIND_PROC_STAT="-b ${config.build.installationDir}${fakeProcStat}:/proc/stat"
  else
    BIND_PROC_STAT=""
  fi

  if [ ! -r /proc/uptime ] && [ -e ${config.build.installationDir}${fakeProcUptime} ]; then
    BIND_PROC_UPTIME="-b ${config.build.installationDir}${fakeProcUptime}:/proc/uptime"
  else
    BIND_PROC_UPTIME=""
  fi

  exec ${config.build.installationDir}/bin/proot-static \
    -b ${config.build.installationDir}/nix:/nix \
    -b ${config.build.installationDir}/bin:/bin! \
    -b ${config.build.installationDir}/etc:/etc! \
    -b ${config.build.installationDir}/tmp:/tmp \
    -b ${config.build.installationDir}/usr:/usr \
    -b ${config.build.installationDir}/dev/shm:/dev/shm \
    $BIND_PROC_STAT \
    $BIND_PROC_UPTIME \
    -b /:/android \
    --link2symlink \
    --sysvipc \
    ${builtins.concatStringsSep " " config.build.extraProotOptions} \
    ${config.build.installationDir}/bin/sh ${config.build.installationDir}/usr/lib/login-inner "$@"
''
