name: check
on:
  push:
    branches:
      - unstable
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-26.04-arm
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: actions/checkout@main
        with:
          repository: ${{ github.actor }}/kudzu
          path: result-kudzu
      - uses: ./result-kudzu/.github/actions/install-nix
      - uses: cachix/cachix-action@master
        continue-on-error: true
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          rm --force ~/.config/nix/nix.conf
          nix flake update
          nix fmt
          nix flake check --impure --print-build-logs
          cd template
          nix flake check --impure --print-build-logs
